// Code generated by MockGen. DO NOT EDIT.
// Source: model_service_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/alishashelby/Samok-Aah-t/backend/internal/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockModelServiceRepository is a mock of ModelServiceRepository interface.
type MockModelServiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockModelServiceRepositoryMockRecorder
}

// MockModelServiceRepositoryMockRecorder is the mock recorder for MockModelServiceRepository.
type MockModelServiceRepositoryMockRecorder struct {
	mock *MockModelServiceRepository
}

// NewMockModelServiceRepository creates a new mock instance.
func NewMockModelServiceRepository(ctrl *gomock.Controller) *MockModelServiceRepository {
	mock := &MockModelServiceRepository{ctrl: ctrl}
	mock.recorder = &MockModelServiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelServiceRepository) EXPECT() *MockModelServiceRepositoryMockRecorder {
	return m.recorder
}

// Deactivate mocks base method.
func (m *MockModelServiceRepository) Deactivate(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockModelServiceRepositoryMockRecorder) Deactivate(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockModelServiceRepository)(nil).Deactivate), ctx, id)
}

// GetAll mocks base method.
func (m *MockModelServiceRepository) GetAll(ctx context.Context, opts *entity.Options, includeInactive bool) ([]*entity.ModelService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, opts, includeInactive)
	ret0, _ := ret[0].([]*entity.ModelService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockModelServiceRepositoryMockRecorder) GetAll(ctx, opts, includeInactive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockModelServiceRepository)(nil).GetAll), ctx, opts, includeInactive)
}

// GetByID mocks base method.
func (m *MockModelServiceRepository) GetByID(ctx context.Context, id int64, includeInactive bool) (*entity.ModelService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, includeInactive)
	ret0, _ := ret[0].(*entity.ModelService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockModelServiceRepositoryMockRecorder) GetByID(ctx, id, includeInactive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockModelServiceRepository)(nil).GetByID), ctx, id, includeInactive)
}

// GetByModelID mocks base method.
func (m *MockModelServiceRepository) GetByModelID(ctx context.Context, modelID int64, opts *entity.Options, includeInactive bool) ([]*entity.ModelService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByModelID", ctx, modelID, opts, includeInactive)
	ret0, _ := ret[0].([]*entity.ModelService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByModelID indicates an expected call of GetByModelID.
func (mr *MockModelServiceRepositoryMockRecorder) GetByModelID(ctx, modelID, opts, includeInactive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByModelID", reflect.TypeOf((*MockModelServiceRepository)(nil).GetByModelID), ctx, modelID, opts, includeInactive)
}

// HasBookings mocks base method.
func (m *MockModelServiceRepository) HasBookings(ctx context.Context, serviceID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasBookings", ctx, serviceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasBookings indicates an expected call of HasBookings.
func (mr *MockModelServiceRepositoryMockRecorder) HasBookings(ctx, serviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasBookings", reflect.TypeOf((*MockModelServiceRepository)(nil).HasBookings), ctx, serviceID)
}

// Save mocks base method.
func (m *MockModelServiceRepository) Save(ctx context.Context, service *entity.ModelService) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockModelServiceRepositoryMockRecorder) Save(ctx, service interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockModelServiceRepository)(nil).Save), ctx, service)
}

// Update mocks base method.
func (m *MockModelServiceRepository) Update(ctx context.Context, service *entity.ModelService) (*entity.ModelService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, service)
	ret0, _ := ret[0].(*entity.ModelService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockModelServiceRepositoryMockRecorder) Update(ctx, service interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockModelServiceRepository)(nil).Update), ctx, service)
}
