// Code generated by MockGen. DO NOT EDIT.
// Source: slot_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/alishashelby/Samok-Aah-t/backend/internal/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockSlotRepository is a mock of SlotRepository interface.
type MockSlotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSlotRepositoryMockRecorder
}

// MockSlotRepositoryMockRecorder is the mock recorder for MockSlotRepository.
type MockSlotRepositoryMockRecorder struct {
	mock *MockSlotRepository
}

// NewMockSlotRepository creates a new mock instance.
func NewMockSlotRepository(ctrl *gomock.Controller) *MockSlotRepository {
	mock := &MockSlotRepository{ctrl: ctrl}
	mock.recorder = &MockSlotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlotRepository) EXPECT() *MockSlotRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockSlotRepository) GetByID(ctx context.Context, id int64) (*entity.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSlotRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSlotRepository)(nil).GetByID), ctx, id)
}

// GetByModelID mocks base method.
func (m *MockSlotRepository) GetByModelID(ctx context.Context, modelID int64) ([]*entity.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByModelID", ctx, modelID)
	ret0, _ := ret[0].([]*entity.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByModelID indicates an expected call of GetByModelID.
func (mr *MockSlotRepositoryMockRecorder) GetByModelID(ctx, modelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByModelID", reflect.TypeOf((*MockSlotRepository)(nil).GetByModelID), ctx, modelID)
}

// GetOverlappingSlots mocks base method.
func (m *MockSlotRepository) GetOverlappingSlots(ctx context.Context, modelID int64, start, end time.Time) ([]*entity.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverlappingSlots", ctx, modelID, start, end)
	ret0, _ := ret[0].([]*entity.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverlappingSlots indicates an expected call of GetOverlappingSlots.
func (mr *MockSlotRepositoryMockRecorder) GetOverlappingSlots(ctx, modelID, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverlappingSlots", reflect.TypeOf((*MockSlotRepository)(nil).GetOverlappingSlots), ctx, modelID, start, end)
}

// Save mocks base method.
func (m *MockSlotRepository) Save(ctx context.Context, slot *entity.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSlotRepositoryMockRecorder) Save(ctx, slot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSlotRepository)(nil).Save), ctx, slot)
}

// Update mocks base method.
func (m *MockSlotRepository) Update(ctx context.Context, slot *entity.Slot) (*entity.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, slot)
	ret0, _ := ret[0].(*entity.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSlotRepositoryMockRecorder) Update(ctx, slot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSlotRepository)(nil).Update), ctx, slot)
}
